# domain: madhurjajoo.com
url: https://madhur-jajoo.github.io # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/jekyll-portfolio" # the subpath of your site, e.g. /blog

sass:
  sass_dir: assets/scss
  style: compressed

# Exclude from processing.
exclude:
  - Dockerfile
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - LICENSE
  - README.md
